import os
class Config(object):
	SECRET_KEY = 'my_token_isac'
	PAGE_ACCES_TOKEN = 'EAAa9ZC2kPMm0BAOqJMhhLBWbGt1cOyodWtPCckJX6b3xmKbUMOXZAeYZCcSZAeWgPVzGQzQCuQvw5aWIsbiiDgZABpdajU8UwvZAMCk32UMLfj4uThWMowlSnEDPKAODt9UvwGiabeJoRl3wlERh43LvyWHqBQ9vdFo7e8drmN7QZDZD'
class DevelopmentConfig(Config):
	DEBUG = True