import os
class Config(object):
	SECRET_KEY = 'my_token_isac'
	PAGE_ACCES_TOKEN = 'EAACyBWgWn4ABAEXHYvlpPqFLCwfvTOuXKJUYweU5clq8NU8W44PfeulmZBdR0sJSTDTCXgtFjbLg21yvwVhRvuT4z5zi9XyXZAIeQipPVw6pT9b9bfoPMsummtLFOBKrN6CEiWk7qGrcZAY6PKbsNfMWAxl5M9M3lxowqZCZA8QZDZD'
class DevelopmentConfig(Config):
	DEBUG = True