import os
class Config(object):
	SECRET_KEY = 'my_token_isac'
	PAGE_ACCES_TOKEN = 'EAAa9ZC2kPMm0BAKDTZCePs9KObYgzoZArlaJuDsG3BCeqZBcKdO2BZAHCmHbsh4RDA6sWM65XQQEuf2nKTSgd7ZBSnus7GAYOCqducF7i15gqm5ZAxWw5QIPEbh6xUa2ZCOZBqcpvK8PGTKwUNirELZCOynn5eP2EJFR4RpoERsrxKsAZDZD'
class DevelopmentConfig(Config):
	DEBUG = True